input.onButtonPressed(Button.A, function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 45)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 45)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 45)
    basic.pause(500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 45)
    basic.pause(1000)
})
input.onButtonPressed(Button.B, function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 45)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 45)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 45)
    basic.pause(500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 45)
    basic.pause(1000)
})
DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
	
})
